<?php
declare(strict_types=1);

namespace Calendar\Test\TestCase\Utility;

use Cake\TestSuite\TestCase;
use Calendar\Utility\IcalFormatter;
use DateTimeImmutable;
use DateTimeZone;
use InvalidArgumentException;

class IcalFormatterTest extends TestCase {

	/**
	 * @return void
	 */
	public function testEscapeBackslashSemicolonCommaNewline(): void {
		$this->assertSame('\\\\', IcalFormatter::escape('\\'));
		$this->assertSame('a\\;b', IcalFormatter::escape('a;b'));
		$this->assertSame('a\\,b', IcalFormatter::escape('a,b'));
		$this->assertSame('a\\nb', IcalFormatter::escape("a\nb"));
		$this->assertSame('a\\nb', IcalFormatter::escape("a\r\nb"));
		$this->assertSame(
			'foo\\\\bar\\;baz\\,qux\\nend',
			IcalFormatter::escape("foo\\bar;baz,qux\nend"),
		);
	}

	/**
	 * @return void
	 */
	public function testFoldLineUnderLimitIsUnchanged(): void {
		$short = 'SUMMARY:Short line';
		$this->assertSame($short, IcalFormatter::foldLine($short));
	}

	/**
	 * @return void
	 */
	public function testFoldLineWrapsAtSeventyFive(): void {
		$line = 'DESCRIPTION:' . str_repeat('X', 200);
		$folded = IcalFormatter::foldLine($line);

		$parts = explode("\r\n", $folded);
		$this->assertGreaterThan(1, count($parts), 'Long line must be folded.');
		$this->assertSame(75, strlen($parts[0]), 'First chunk is 75 octets.');
		foreach (array_slice($parts, 1) as $cont) {
			$this->assertStringStartsWith(' ', $cont, 'Continuation lines start with a space.');
			$this->assertLessThanOrEqual(75, strlen($cont), 'Continuation chunks (incl. leading space) stay <= 75 octets.');
		}

		$rejoined = str_replace("\r\n ", '', $folded);
		$this->assertSame($line, $rejoined, 'Unfolding the chunks reconstructs the original line.');
	}

	/**
	 * @return void
	 */
	public function testFormatDateTimeIsAlwaysUTC(): void {
		$dt = new DateTimeImmutable('2026-05-12 14:30:00', new DateTimeZone('Europe/Berlin'));
		$this->assertSame('20260512T123000Z', IcalFormatter::formatDateTime($dt));
	}

	/**
	 * @return void
	 */
	public function testFormatEventRequiresStart(): void {
		$this->expectException(InvalidArgumentException::class);
		IcalFormatter::formatEvent(['summary' => 'Missing start']);
	}

	/**
	 * @return void
	 */
	public function testFormatEventTimedShape(): void {
		$out = IcalFormatter::formatEvent([
			'uid' => 'fixed-uid-1',
			'summary' => 'Lunch',
			'location' => 'Cafe',
			'description' => 'Catch up',
			'start' => new DateTimeImmutable('2026-05-12 12:00:00', new DateTimeZone('UTC')),
			'end' => new DateTimeImmutable('2026-05-12 13:00:00', new DateTimeZone('UTC')),
		]);

		$this->assertStringContainsString("BEGIN:VEVENT\r\n", $out);
		$this->assertStringContainsString('END:VEVENT', $out);
		$this->assertStringContainsString('UID:fixed-uid-1', $out);
		$this->assertStringContainsString('DTSTART:20260512T120000Z', $out);
		$this->assertStringContainsString('DTEND:20260512T130000Z', $out);
		$this->assertStringContainsString('SUMMARY:Lunch', $out);
		$this->assertStringContainsString('LOCATION:Cafe', $out);
		$this->assertStringContainsString('DESCRIPTION:Catch up', $out);
		$this->assertStringContainsString('DTSTAMP:', $out);
	}

	/**
	 * All-day events must use `;VALUE=DATE:YYYYMMDD` per §3.6.1, not the
	 * UTC instant form.
	 *
	 * @return void
	 */
	public function testFormatEventAllDayShape(): void {
		$out = IcalFormatter::formatEvent([
			'uid' => 'allday-1',
			'summary' => 'Birthday',
			'start' => '2026-05-12',
			'allDay' => true,
		]);

		$this->assertStringContainsString('DTSTART;VALUE=DATE:20260512', $out);
		$this->assertStringNotContainsString('DTSTART:20260512T', $out);
	}

	/**
	 * @return void
	 */
	public function testFormatEventEscapesTextFields(): void {
		$out = IcalFormatter::formatEvent([
			'uid' => 'esc-1',
			'summary' => 'Meet; Bob, and discuss A\\B',
			'description' => "Line1\nLine2",
			'start' => '2026-05-12 12:00:00',
		]);

		$this->assertStringContainsString('SUMMARY:Meet\\; Bob\\, and discuss A\\\\B', $out);
		$this->assertStringContainsString('DESCRIPTION:Line1\\nLine2', $out);
	}

	/**
	 * @return void
	 */
	public function testFormatEventOmitsBlankOptionalFields(): void {
		$out = IcalFormatter::formatEvent([
			'uid' => 'min-1',
			'start' => '2026-05-12 12:00:00',
		]);

		$this->assertStringNotContainsString('SUMMARY:', $out);
		$this->assertStringNotContainsString('DESCRIPTION:', $out);
		$this->assertStringNotContainsString('LOCATION:', $out);
		$this->assertStringNotContainsString('URL:', $out);
		$this->assertStringNotContainsString('CATEGORIES:', $out);
		$this->assertStringNotContainsString('DTEND:', $out);
	}

	/**
	 * @return void
	 */
	public function testAutoGeneratedUidIsStableForSameInput(): void {
		$base = [
			'summary' => 'Standup',
			'location' => 'Zoom',
			'start' => '2026-05-12 09:00:00',
		];

		$out1 = IcalFormatter::formatEvent($base);
		$out2 = IcalFormatter::formatEvent($base);

		preg_match('/UID:([^\r\n]+)/', $out1, $m1);
		preg_match('/UID:([^\r\n]+)/', $out2, $m2);

		$this->assertSame($m1[1], $m2[1], 'Same payload must yield the same auto-generated UID.');
		$this->assertStringEndsWith('@cakephp-calendar', $m1[1]);
	}

	/**
	 * @return void
	 */
	public function testFormatCalendarWrapsEvents(): void {
		$out = IcalFormatter::formatCalendar([
			['uid' => 'a', 'summary' => 'A', 'start' => '2026-05-12 10:00:00'],
			['uid' => 'b', 'summary' => 'B', 'start' => '2026-05-12 11:00:00'],
		], ['prodid' => '-//Acme//Events//EN']);

		$this->assertStringStartsWith("BEGIN:VCALENDAR\r\n", $out);
		$this->assertStringEndsWith("END:VCALENDAR\r\n", $out);
		$this->assertStringContainsString('PRODID:-//Acme//Events//EN', $out);
		$this->assertStringContainsString('VERSION:2.0', $out);
		$this->assertStringContainsString('UID:a', $out);
		$this->assertStringContainsString('UID:b', $out);
		$this->assertSame(2, substr_count($out, 'BEGIN:VEVENT'));
		$this->assertSame(2, substr_count($out, 'END:VEVENT'));
	}

	/**
	 * Every content line MUST end with CRLF (§3.1). Validate via a single
	 * scan rather than asserting per-property.
	 *
	 * @return void
	 */
	public function testCalendarOutputUsesCrlfLineEndings(): void {
		$out = IcalFormatter::formatCalendar([
			['uid' => 'crlf-1', 'summary' => 'X', 'start' => '2026-05-12 10:00:00'],
		]);
		$this->assertStringNotContainsString("\n\n", $out);
		// CRLF-only — never a bare \n outside a folded continuation or escape.
		$bareNewlines = preg_match_all('/(?<!\r)\n/', $out);
		$this->assertSame(0, $bareNewlines, 'iCal output must use CRLF, not bare LF.');
	}

	/**
	 * @return void
	 */
	public function testCategoriesArrayBecomesCommaSeparated(): void {
		$out = IcalFormatter::formatEvent([
			'uid' => 'cat-1',
			'summary' => 'Tagged',
			'start' => '2026-05-12 10:00:00',
			'categories' => ['Work', 'Standup', 'Foo, Bar'],
		]);

		$this->assertStringContainsString('CATEGORIES:Work,Standup,Foo\\, Bar', $out);
	}

}
